### ISSUE TITLE
Password Encryption

### ISSUE THREAD

**Issue by somT-oss** [GitHub-Campus-Experts-Unilag/Password-Manager#2]
### What is Needed
Contributors are expected to finish the ```encrypt_password``` method implementation

### How to Contribute
 - Get familiar with the scripts and documentation already provided in the [repository](https://github.com/GitHub-Campus-Experts-Unilag/Password-Manager).
 - Test your code: It is pertinent that you check your code runs smoothly before making a pull request.
 - Create a Pull Request: Submit a pull request to the repository with your code in the appropriate script and include any necessary documentation.
 
 We are excited to see your contributions! Happy Hacking! 🎉

**Comment by abhijeetballabh** [comment]
Hey @somT-oss , please assign this issue to me.

**Comment by somT-oss** [comment]
Hi @abhijeetballabh , issues are not assigned to one person particularly. 
If you are interested in contributing to the project, feel free to start contributing. Make sure to follow the guidelines for the contributions. 

Happy hacking!!

**Comment by David3Emmanuel** [comment]
@somT-oss, I've created a pull request for this (#3)

**Comment by somT-oss** [comment]
> @somT-oss, I've created a pull request for this (#3)

Nice work, the PR has been merged.

**Comment by somT-oss** [comment]
@David3Emmanuel please check if your contribution has been recorded for hacktoberfest

**Comment by David3Emmanuel** [comment]
> @David3Emmanuel please check if your contribution has been recorded for hacktoberfest

Yes, but according to HacktoberFest, the repository is not participating.

> "Your PR was submitted to a repository that is not participating in HacktoberFest. Maintainers need to add the hacktoberfest topic to the repository, or add the hacktoberfest-accepted label to your PR"
